version: 2.1

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  determine-workflow:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Determine which workflow to run
          command: |
            if [[ "${CIRCLE_JOB}" == "test-success" ]]; then
              echo 'export PARAM_RUN_SUCCESS_WORKFLOW=true' >> $BASH_ENV
            elif [[ "${CIRCLE_JOB}" == "test-failure" ]]; then
              echo 'export PARAM_RUN_FAILURE_WORKFLOW=true' >> $BASH_ENV
            fi

workflows:
  main:
    jobs:
      - determine-workflow:
          requires:
            - test-success
            - test-failure
      - continuation/continue:
          requires:
            - determine-workflow
          configuration_path: .circleci/anchit_success_workflow.yml
          condition: << pipeline.parameters.run_success_workflow >>
      - continuation/continue:
          requires:
            - determine-workflow
          configuration_path: .circleci/anchit_failure_workflow.yml
          condition: << pipeline.parameters.run_failure_workflow >>
