version: 2.1

jobs:
  next-job:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Next job"
          command: "echo This workflow should pass!"

workflows:
  next-workflow:
    jobs:
      - next-job
