# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-dev-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test dev build"
          command: "echo Testing dev build"

  test-dev-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test dev deploy"
          command: "echo Testing dev deploy"

  test-staging-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test staging build"
          command: "echo Testing staging build"

  test-staging-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test staging deploy"
          command: "echo Testing staging deploy"

  test-prod-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test prod build"
          command: "echo Testing prod build"

  test-prod-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test prod deploy"
          command: "echo Testing prod deploy"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  dev-test-workflow:
    jobs:
      - test-dev-build
      - test-dev-deploy

  staging-test-workflow:
    jobs:
      - test-staging-build
      - test-staging-deploy

  prod-test-workflow:
    jobs:
      - test-prod-build
      - test-prod-deploy

  dev-staging-prod-single-workflow:
    jobs:
      - test-dev-build
      - test-dev-deploy:
          requires:
            - test-dev-build
      - test-staging-build:
          requires:
            - test-dev-deploy
      - test-staging-deploy:
          requires:
            - test-staging-build
      - test-prod-build:
          requires:
            - test-staging-deploy
      - test-prod-deploy:
          requires:
            - test-prod-build
