# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-backend:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test backend"
          command: "echo Testing backend"

  failure-path:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Testing a failure"
          command: "echo Testing a failure"

  test-frontend:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test frontend"
          command: "echo Testing frontend"
  system-checks:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test system checks"
          command: "echo Testing system checks"
  dev-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test dev build"
          command: "echo Testing dev build"

  dev-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test dev deploy"
          command: "echo Testing dev deploy"

  staging-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test staging build"
          command: "echo Testing staging build"

  staging-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test staging deploy"
          command: "echo Testing staging deploy"

  prod-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test prod build"
          command: "echo Testing prod build"

  prod-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Test prod deploy"
          command: "echo Testing prod deploy"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  dev-staging-prod-single-workflow:
    - test-backend:
        on_fail:
          - failure-path
    - test-frontend:
        on_fail:
      -  failure-path
    - system-checks:
        on_fail:
      -  failure-path
    - dev-build:
        requires:
      - test-backend
      - test-frontend
      - system-checks  - dev-deploy:
          requires:
            - dev-build
      - staging-build:
          requires:
            - dev-deploy
      - staging-deploy:
          requires:
            - staging-build
      - prod-build:
          type: approval
          requires:
            - staging-deploy
      - prod-deploy:
          requires:
            - prod-build
