# Use the latest 2.1 version of CircleCI pipeline process engine.
workflows:
  dev-staging-prod-single-workflow:
    - test-backend
    - test-frontend
    - system-checks
    - dev-build:
        requires:
      - test-backend
      - test-frontend
      - system-checks
    - dev-deploy:
        requires:
      - dev-build
    - staging-build:
        requires:
      - dev-deploy
    - staging-deploy:
        requires:
      - staging-build
    - prod-build:
        requires:
      - staging-deploy
        filters:
      branches:
        only:
          - /^manual-trigger$/
    - prod-deploy:
        requires:
      - prod-build