name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch: # This allows you to manually trigger the workflow via a button in the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Production
      run: |
        # Add your deployment commands here, e.g., using SSH or any deployment tool you prefer
        echo "Deploying to production..."
        # Example: scp -r ./build user@server:/path/to/deploy
